name: particle_clock
description: Mickel's entry for the Flutter Clock challenge.
publish_to: none
version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  cached_network_image: ^3.3.1
  change_app_package_name: ^1.1.0
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.9
  fullscreen_window: ^1.0.4
  geolocator: ^10.1.0
  one_clock: ^2.0.0
  weather: ^3.1.1

flutter_launcher_icons:
  image_path: "assets/icon-378x378.png"
  android: true # can specify file name here e.g. "ic_launcher"
  ios: true # can specify file name here e.g. "My-Launcher-Icon"
  min_sdk_android: 21 # android min sdk min:16, default 21
  remove_alpha_ios: true
  background_color_ios: "#ffffff"

flutter_native_splash:
  color: "#ffffff"
  image: assets/LaunchScreen.png
  android_12:
    image: assets/LaunchScreen.png
    icon_background_color: "#ffffff"
  ios_content_mode: scaleAspectFill
  web: false

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - assets/palettes.json